title: Welcome to my notes
theme: just-the-docs
url: https://wuao1999.github.io/Notes
plugins:
  - jekyll-default-layout
aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/wuao1999/Notes
markdown: kramdown
math: mathjax
kramdown:
  math_engine: mathjax
